// HT45F0002.h
//	This file contains the definition of registers for
//		Holtek HT45F0002 microcontroller.
//	Generated by HTFileParse.dll.
//	Do not modify manually.

#ifndef _HT45F0002_H_
#define _HT45F0002_H_

unsigned char _iar0	@0x00;
unsigned char _mp0	@0x01;
unsigned char _iar1	@0x02;
unsigned char _mp1l	@0x03;
unsigned char _mp1h	@0x04;
unsigned char _acc	@0x05;
unsigned char _pcl	@0x06;
unsigned char _tblp	@0x07;
unsigned char _tblh	@0x08;
unsigned char _tbhp	@0x09;
unsigned char _status	@0x0A;
unsigned char _iar2	@0x0C;
unsigned char _mp2l	@0x0D;
unsigned char _mp2h	@0x0E;
unsigned char _scc	@0x0F;
unsigned char _intc0	@0x10;
unsigned char _intc1	@0x11;
unsigned char _intc2	@0x12;
unsigned char _intc3	@0x13;
unsigned char _pa	@0x14;
unsigned char _pac	@0x15;
unsigned char _papu	@0x16;
unsigned char _pawu	@0x17;
unsigned char _mfi0	@0x18;
unsigned char _mfi1	@0x1C;
unsigned char _mfi2	@0x1D;
unsigned char _mfi3	@0x1E;
unsigned char _wdtc	@0x1F;
unsigned char _rstfc	@0x20;
unsigned char _lvrc	@0x21;
unsigned char _lvdc	@0x22;
unsigned char _integ	@0x23;
unsigned char _tbc	@0x24;
unsigned char _eea	@0x25;
unsigned char _eed	@0x26;
unsigned char _pc	@0x27;
unsigned char _pcc	@0x28;
unsigned char _pcpu	@0x29;
unsigned char _ctm0c0	@0x2A;
unsigned char _ctm0c1	@0x2B;
unsigned char _ctm0dl	@0x2C;
unsigned char _ctm0dh	@0x2D;
unsigned char _ctm0al	@0x2E;
unsigned char _ctm0ah	@0x2F;
unsigned char _ptm0c0	@0x30;
unsigned char _ptm0c1	@0x31;
unsigned char _ptm0dl	@0x32;
unsigned char _ptm0dh	@0x33;
unsigned char _ptm0al	@0x34;
unsigned char _ptm0ah	@0x35;
unsigned char _ptm0rpl	@0x36;
unsigned char _ptm0rph	@0x37;
unsigned char _iicc0	@0x38;
unsigned char _iicc1	@0x39;
unsigned char _iicd	@0x3A;
unsigned char _iica	@0x3B;
unsigned char _iictoc	@0x3C;
unsigned char _sadol	@0x40;
unsigned char _sadoh	@0x41;
unsigned char _sadc0	@0x42;
unsigned char _sadc1	@0x43;
unsigned char _sadc2	@0x44;
unsigned char _pb	@0x45;
unsigned char _pbc	@0x46;
unsigned char _pbpu	@0x47;
unsigned char _pbs0	@0x48;
unsigned char _ppgc	@0x49;
unsigned char _ppgpc	@0x4A;
unsigned char _ppgta	@0x4B;
unsigned char _ppgtb	@0x4C;
unsigned char _ppgtex	@0x4D;
unsigned char _pwlt	@0x4E;
unsigned char _tdc	@0x4F;
unsigned char _ctm1c0	@0x50;
unsigned char _ctm1c1	@0x51;
unsigned char _ctm1dl	@0x52;
unsigned char _ctm1dh	@0x53;
unsigned char _ctm1al	@0x54;
unsigned char _ctm1ah	@0x55;
unsigned char _u0sr	@0x58;
unsigned char _u0cr1	@0x59;
unsigned char _u0cr2	@0x5A;
unsigned char _txr_rxr0	@0x5B;
unsigned char _brg0	@0x5C;
unsigned char _ppgctc	@0x60;
unsigned char _syncbuf	@0x61;
unsigned char _pckc	@0x62;
unsigned char _ctrl	@0x63;
unsigned char _pcs0	@0x64;
unsigned char _pcs1	@0x65;
unsigned char _cmp1c2	@0x66;
unsigned char _cmp3c2	@0x67;
unsigned char _cmp0c0	@0x68;
unsigned char _cmp0c1	@0x69;
unsigned char _cmp0c2	@0x6A;
unsigned char _cmp0c3	@0x6B;
unsigned char _hircc	@0x6C;
unsigned char _cmp1c0	@0x6D;
unsigned char _cmp1c1	@0x6E;
unsigned char _cmp1da	@0x6F;
unsigned char _cmp2c0	@0x70;
unsigned char _cmp2c1	@0x71;
unsigned char _cmp2da	@0x72;
unsigned char _cmp3c0	@0x73;
unsigned char _cmp3c1	@0x74;
unsigned char _cmp3da	@0x75;
unsigned char _cmp4c0	@0x76;
unsigned char _cmp4c1	@0x77;
unsigned char _cmp4c2	@0x78;
unsigned char _cmp4da	@0x79;
unsigned char _opac0	@0x7A;
unsigned char _opac1	@0x7B;
unsigned char _pas0	@0x7C;
unsigned char _pas1	@0x7D;
unsigned char _tmr	@0x7E;
unsigned char _tmrc	@0x7F;
#define _eec	_0140

#define _c	_0a_0
#define _ac	_0a_1
#define _z	_0a_2
#define _ov	_0a_3
#define _pdf	_0a_4
#define _to	_0a_5
#define _cz	_0a_6
#define _sc	_0a_7
#define _fsiden	_0f_0
#define _fhiden	_0f_1
#define _cks0	_0f_5
#define _cks1	_0f_6
#define _cks2	_0f_7
#define _emi	_10_0
#define _int0e	_10_1
#define _cp0e	_10_2
#define _cp1e	_10_3
#define _int0f	_10_4
#define _cp0f	_10_5
#define _cp1f	_10_6
#define _cp2e	_11_0
#define _cp3e	_11_1
#define _cp4e	_11_2
#define _synce	_11_3
#define _cp2f	_11_4
#define _cp3f	_11_5
#define _cp4f	_11_6
#define _syncf	_11_7
#define _iice	_12_0
#define _mf0e	_12_1
#define _tb1e	_12_2
#define _te	_12_3
#define _iicf	_12_4
#define _mf0f	_12_5
#define _tb1f	_12_6
#define _tf	_12_7
#define _ur0e	_13_0
#define _mf1e	_13_1
#define _mf2e	_13_2
#define _mf3e	_13_3
#define _ur0f	_13_4
#define _mf1f	_13_5
#define _mf2f	_13_6
#define _mf3f	_13_7
#define _pa0	_14_0
#define _pa1	_14_1
#define _pa2	_14_2
#define _pa3	_14_3
#define _pa4	_14_4
#define _pa5	_14_5
#define _pa6	_14_6
#define _pa7	_14_7
#define _pac0	_15_0
#define _pac1	_15_1
#define _pac2	_15_2
#define _pac3	_15_3
#define _pac4	_15_4
#define _pac5	_15_5
#define _pac6	_15_6
#define _pac7	_15_7
#define _papu0	_16_0
#define _papu1	_16_1
#define _papu2	_16_2
#define _papu3	_16_3
#define _papu4	_16_4
#define _papu5	_16_5
#define _papu6	_16_6
#define _papu7	_16_7
#define _pawu0	_17_0
#define _pawu1	_17_1
#define _pawu2	_17_2
#define _pawu3	_17_3
#define _pawu4	_17_4
#define _pawu5	_17_5
#define _pawu6	_17_6
#define _pawu7	_17_7
#define _ptm0pe	_18_0
#define _ptm0ae	_18_1
#define _tb0e	_18_2
#define _ptm0pf	_18_4
#define _ptm0af	_18_5
#define _tb0f	_18_6
#define _ctm0pe	_1c_0
#define _ctm0ae	_1c_1
#define _ade	_1c_2
#define _ctm0pf	_1c_4
#define _ctm0af	_1c_5
#define _adf	_1c_6
#define _ctm1pe	_1d_0
#define _ctm1ae	_1d_1
#define _dee	_1d_2
#define _ctm1pf	_1d_4
#define _ctm1af	_1d_5
#define _def	_1d_6
#define _int1e	_1e_0
#define _lve	_1e_1
#define _int1f	_1e_4
#define _lvf	_1e_5
#define _ws0	_1f_0
#define _ws1	_1f_1
#define _ws2	_1f_2
#define _we0	_1f_3
#define _we1	_1f_4
#define _we2	_1f_5
#define _we3	_1f_6
#define _we4	_1f_7
#define _wrf	_20_0
#define _lrf	_20_1
#define _lvrf	_20_2
#define _lvs0	_21_0
#define _lvs1	_21_1
#define _lvs2	_21_2
#define _lvs3	_21_3
#define _lvs4	_21_4
#define _lvs5	_21_5
#define _lvs6	_21_6
#define _lvs7	_21_7
#define _vlvd0	_22_0
#define _vlvd1	_22_1
#define _vlvd2	_22_2
#define _vbgen	_22_3
#define _lvden	_22_4
#define _lvdo	_22_5
#define _int0s0	_23_0
#define _int0s1	_23_1
#define _int1s0	_23_2
#define _int1s1	_23_3
#define _tb00	_24_0
#define _tb01	_24_1
#define _tb02	_24_2
#define _tb10	_24_4
#define _tb11	_24_5
#define _tbck	_24_6
#define _tbon	_24_7
#define _pc0	_27_0
#define _pc1	_27_1
#define _pc2	_27_2
#define _pc3	_27_3
#define _pc4	_27_4
#define _pcc0	_28_0
#define _pcc1	_28_1
#define _pcc2	_28_2
#define _pcc3	_28_3
#define _pcc4	_28_4
#define _pcpu0	_29_0
#define _pcpu1	_29_1
#define _pcpu2	_29_2
#define _pcpu3	_29_3
#define _pcpu4	_29_4
#define _ct0rp0	_2a_0
#define _ct0rp1	_2a_1
#define _ct0rp2	_2a_2
#define _ct0on	_2a_3
#define _ct0ck0	_2a_4
#define _ct0ck1	_2a_5
#define _ct0ck2	_2a_6
#define _ct0pau	_2a_7
#define _ct0cclr	_2b_0
#define _ct0dpx	_2b_1
#define _ct0pol	_2b_2
#define _ct0oc	_2b_3
#define _ct0io0	_2b_4
#define _ct0io1	_2b_5
#define _ct0m0	_2b_6
#define _ct0m1	_2b_7
#define _pt0on	_30_3
#define _pt0ck0	_30_4
#define _pt0ck1	_30_5
#define _pt0ck2	_30_6
#define _pt0pau	_30_7
#define _pt0cclr	_31_0
#define _pt0capts	_31_1
#define _pt0pol	_31_2
#define _pt0oc	_31_3
#define _pt0io0	_31_4
#define _pt0io1	_31_5
#define _pt0m0	_31_6
#define _pt0m1	_31_7
#define _iicen	_38_1
#define _iicdeb0	_38_2
#define _iicdeb1	_38_3
#define _rxak	_39_0
#define _iamwu	_39_1
#define _srw	_39_2
#define _txak	_39_3
#define _htx	_39_4
#define _hbb	_39_5
#define _haas	_39_6
#define _hcf	_39_7
#define _a0	_3b_1
#define _a1	_3b_2
#define _a2	_3b_3
#define _a3	_3b_4
#define _a4	_3b_5
#define _a5	_3b_6
#define _a6	_3b_7
#define _iictos0	_3c_0
#define _iictos1	_3c_1
#define _iictos2	_3c_2
#define _iictos3	_3c_3
#define _iictos4	_3c_4
#define _iictos5	_3c_5
#define _iictof	_3c_6
#define _iictoen	_3c_7
#define _sacs0	_42_0
#define _sacs1	_42_1
#define _sacs2	_42_2
#define _sacs3	_42_3
#define _adrfs	_42_4
#define _adcen	_42_5
#define _adbz	_42_6
#define _start	_42_7
#define _sacks0	_43_0
#define _sacks1	_43_1
#define _sacks2	_43_2
#define _sains0	_43_4
#define _sains1	_43_5
#define _sains2	_43_6
#define _sains3	_43_7
#define _pgags0	_44_0
#define _pgags1	_44_1
#define _savrs0	_44_2
#define _savrs1	_44_3
#define _pgais	_44_4
#define _verify0	_44_5
#define _adpgaen	_44_7
#define _pb0	_45_0
#define _pb1	_45_1
#define _pb2	_45_2
#define _pb3	_45_3
#define _pbc0	_46_0
#define _pbc1	_46_1
#define _pbc2	_46_2
#define _pbc3	_46_3
#define _pbpu0	_47_0
#define _pbpu1	_47_1
#define _pbpu2	_47_2
#define _pbpu3	_47_3
#define _pbs00	_48_0
#define _pbs01	_48_1
#define _pbs02	_48_2
#define _pbs03	_48_3
#define _pcsd	_49_0
#define _trgmod	_49_1
#define _ptsyn	_49_3
#define _rlbf	_49_4
#define _prsen	_49_6
#define _pst	_49_7
#define _ppgpc0	_4a_0
#define _ppgpc1	_4a_1
#define _ppgpc2	_4a_2
#define _ppgpc3	_4a_3
#define _ppgpc4	_4a_4
#define _ppgpc5	_4a_5
#define _ppgpc6	_4a_6
#define _ppgpc7	_4a_7
#define _ppgta0	_4b_0
#define _ppgta1	_4b_1
#define _ppgta2	_4b_2
#define _ppgta3	_4b_3
#define _ppgta4	_4b_4
#define _ppgta5	_4b_5
#define _ppgta6	_4b_6
#define _ppgta7	_4b_7
#define _ppgtb0	_4c_0
#define _ppgtb1	_4c_1
#define _ppgtb2	_4c_2
#define _ppgtb3	_4c_3
#define _ppgtb4	_4c_4
#define _ppgtb5	_4c_5
#define _ppgtb6	_4c_6
#define _ppgtb7	_4c_7
#define _ppgta8	_4d_0
#define _ppgtb8	_4d_4
#define _tdps0	_4f_0
#define _tdps1	_4f_1
#define _tdugs0	_4f_2
#define _tdugs1	_4f_3
#define _tdccs0	_4f_4
#define _tdccs1	_4f_5
#define _tdcce	_4f_6
#define _tduge	_4f_7
#define _ct1rp0	_50_0
#define _ct1rp1	_50_1
#define _ct1rp2	_50_2
#define _ct1on	_50_3
#define _ct1ck0	_50_4
#define _ct1ck1	_50_5
#define _ct1ck2	_50_6
#define _ct1pau	_50_7
#define _ct1cclr	_51_0
#define _ct1dpx	_51_1
#define _ct1pol	_51_2
#define _ct1oc	_51_3
#define _ct1io0	_51_4
#define _ct1io1	_51_5
#define _ct1m0	_51_6
#define _ct1m1	_51_7
#define _txif0	_58_0
#define _tidle0	_58_1
#define _rxif0	_58_2
#define _ridle0	_58_3
#define _oerr0	_58_4
#define _ferr0	_58_5
#define _nf0	_58_6
#define _perr0	_58_7
#define _tx80	_59_0
#define _rx80	_59_1
#define _txbrk0	_59_2
#define _stops0	_59_3
#define _prt0	_59_4
#define _pren0	_59_5
#define _bno0	_59_6
#define _uarten0	_59_7
#define _teie0	_5a_0
#define _tiie0	_5a_1
#define _rie0	_5a_2
#define _wake0	_5a_3
#define _adden0	_5a_4
#define _brgh0	_5a_5
#define _rxen0	_5a_6
#define _txen0	_5a_7
#define _cts0	_60_0
#define _cts1	_60_1
#define _cton	_60_2
#define _ctf	_60_3
#define _pckpsc0	_62_0
#define _pckpsc1	_62_1
#define _pckpsc2	_62_2
#define _pckpsc3	_62_3
#define _pcken	_62_4
#define _pckpol	_62_5
#define _pckd	_62_6
#define _sdapc	_63_3
#define _sclpc	_63_4
#define _rxpc	_63_5
#define _tdccs2	_63_6
#define _pcs00	_64_0
#define _pcs01	_64_1
#define _pcs02	_64_2
#define _pcs03	_64_3
#define _pcs04	_64_4
#define _pcs05	_64_5
#define _pcs06	_64_6
#define _pcs07	_64_7
#define _pcs10	_65_0
#define _pcs11	_65_1
#define _c1eg0	_66_6
#define _c1eg1	_66_7
#define _c3eg0	_67_6
#define _c3eg1	_67_7
#define _c0csw	_68_1
#define _c0rsw	_68_2
#define _c0o	_68_3
#define _c0chy	_68_4
#define _c0en	_68_5
#define _c0eg0	_68_6
#define _c0eg1	_68_7
#define _c0of0	_69_0
#define _c0of1	_69_1
#define _c0of2	_69_2
#define _c0of3	_69_3
#define _c0of4	_69_4
#define _c0rs	_69_5
#define _c0ofm	_69_6
#define _c0cx	_69_7
#define _c0db0	_6a_0
#define _c0db1	_6a_1
#define _c0db2	_6a_2
#define _c0db3	_6a_3
#define _c0db4	_6a_4
#define _c0db5	_6a_5
#define _ppgdl0	_6b_0
#define _ppgdl1	_6b_1
#define _ppgdl2	_6b_2
#define _ppgdl3	_6b_3
#define _ppgdl4	_6b_4
#define _ppgdl5	_6b_5
#define _hircen	_6c_0
#define _hircf	_6c_1
#define _c1db0	_6d_0
#define _c1db1	_6d_1
#define _c1rv	_6d_2
#define _c1o	_6d_3
#define _c1chy	_6d_4
#define _c1en	_6d_5
#define _c1rlen	_6d_6
#define _pspc1e	_6d_7
#define _c1of0	_6e_0
#define _c1of1	_6e_1
#define _c1of2	_6e_2
#define _c1of3	_6e_3
#define _c1of4	_6e_4
#define _c1rs	_6e_5
#define _c1ofm	_6e_6
#define _c1cx	_6e_7
#define _c2db0	_70_0
#define _c2db1	_70_1
#define _c2rv	_70_2
#define _c2o	_70_3
#define _c2chy	_70_4
#define _c2en	_70_5
#define _c2eg0	_70_6
#define _c2eg1	_70_7
#define _c2of0	_71_0
#define _c2of1	_71_1
#define _c2of2	_71_2
#define _c2of3	_71_3
#define _c2of4	_71_4
#define _c2rs	_71_5
#define _c2ofm	_71_6
#define _c2cx	_71_7
#define _c3db0	_73_0
#define _c3db1	_73_1
#define _c3rv	_73_2
#define _c3o	_73_3
#define _c3chy	_73_4
#define _c3en	_73_5
#define _pspc3e	_73_7
#define _c3of0	_74_0
#define _c3of1	_74_1
#define _c3of2	_74_2
#define _c3of3	_74_3
#define _c3of4	_74_4
#define _c3rs	_74_5
#define _c3ofm	_74_6
#define _c3cx	_74_7
#define _c4db0	_76_0
#define _c4db1	_76_1
#define _c4rv	_76_2
#define _c4o	_76_3
#define _c4chy	_76_4
#define _c4en	_76_5
#define _c4rlen	_76_6
#define _pspc4e	_76_7
#define _c4of0	_77_0
#define _c4of1	_77_1
#define _c4of2	_77_2
#define _c4of3	_77_3
#define _c4of4	_77_4
#define _c4rs	_77_5
#define _c4ofm	_77_6
#define _c4cx	_77_7
#define _c4pc0	_78_0
#define _c4pc1	_78_1
#define _c4eg0	_78_6
#define _c4eg1	_78_7
#define _opax	_7a_0
#define _swr1	_7a_1
#define _swr2	_7a_2
#define _opag0	_7a_3
#define _opag1	_7a_4
#define _opag2	_7a_5
#define _opam0	_7a_6
#define _opam1	_7a_7
#define _aof0	_7b_0
#define _aof1	_7b_1
#define _aof2	_7b_2
#define _aof3	_7b_3
#define _aof4	_7b_4
#define _aof5	_7b_5
#define _ars	_7b_6
#define _aofm	_7b_7
#define _pas00	_7c_0
#define _pas01	_7c_1
#define _pas02	_7c_2
#define _pas03	_7c_3
#define _pas04	_7c_4
#define _pas05	_7c_5
#define _pas06	_7c_6
#define _pas07	_7c_7
#define _pas10	_7d_0
#define _pas11	_7d_1
#define _pas12	_7d_2
#define _pas13	_7d_3
#define _pas14	_7d_4
#define _pas15	_7d_5
#define _pas16	_7d_6
#define _pas17	_7d_7
#define _tpsc0	_7f_0
#define _tpsc1	_7f_1
#define _tpsc2	_7f_2
#define _ton	_7f_4
#define _tm0	_7f_6
#define _tm1	_7f_7
#define _rd	_140_0
#define _rden	_140_1
#define _wr	_140_2
#define _wren	_140_3


#endif // _HT45F0002_H_
